### ISSUE TITLE
The 'Fork me on Github' is too big and covers the 'Elisp' tab.

### ISSUE THREAD

**Issue by jiegec** [zilongshanren/about.emacs-china.org#3]
When the page is rendered in iPad mini in Vertical Mode where the width of the window is not enough to hold all tabs, the tabs are separated into two rows, the rightmost of the first row covered by the 'Fork me on Github' banner.

**Comment by jiegec** [comment]
By the way, I dislike the SinglePaged Theme. I would prefer the style of the official Emacs Website.

**Comment by zilongshanren** [comment]
@jiegec  You could propose a better theme 😄   I also like the Emacs Website, but I"m not a Front End guy, please help

**Comment by zilongshanren** [comment]
@jiegec  我把主页的主题重新 设计了一下，这样应该好看多了。

**Comment by jiegec** [comment]
Great.
